services:

  # Database
  Database:
    image: postgres:13
    container_name: birdcage-database
    restart: always
    ports:
      - "9033:5432"
    volumes:
      - ./database:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - bridge
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Server
  server:
    container_name: birdcage-server
    build: server
    restart: always
    ports:
      - "3000:80"
    environment:
      - DATABASE_URL=postgres://postgres:password@birdcage-database/postgres
      - origin=https://bird.hootsifer.com
    networks:
      - bridge

  # Client
  client:
    container_name: birdcage-client
    build: client
    restart: always
    environment:
      # NOTE
      - ORIGIN=https://bird.hootsifer.com
    networks:
      - bridge

  # NGINX proxy
  proxy:
    image: nginx:alpine
    container_name: birdcage-proxy
    ports:
      - "82:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - bridge
      - nginx

networks:
  bridge:
  nginx:
    external: true
    name: nginx
