services:

  # Database
  Database:
    container_name: birdcage-database
    image: influxdb:2
    restart: always
    ports:
      - "8086:8086"
    environment:
      - username=admin
      - password=password
    volumes:
      - ./database/data:/var/lib/influxdb
      - ./database/config:/etc/influxdb
    networks:
      - bridge

  # Server
  server:
    container_name: birdcage-server
    build: server
    restart: always
    environment:
      - db_host="http://birdcage-database:8086"
      - db_org="bird"
      - db_token="sdDU9Wv8IqSgK37X8PYOGUQ8wF_QvE560lSlFowHBjz41olKk3Uzwti0oTnqTBtwxiS6DpEk4FHaDLWaQIHAZg=="
      - db_bucket="sensor_data"
      - origin=https://bird.hootsifer.com
    networks:
      - bridge

  # Client
  client:
    container_name: birdcage-client
    build: client
    restart: always
    environment:
      # NOTE
      - ORIGIN=https://bird.hootsifer.com
    networks:
      - bridge

  # NGINX proxy
  proxy:
    image: nginx:alpine
    container_name: birdcage-proxy
    ports:
      - "82:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - bridge
      - nginx

networks:
  bridge:
  nginx:
    external: true
    name: nginx
