[package]
name = "smart-bird-cage-server"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = "thin"
strip = true


[dependencies]
[dependencies.rocket]
version = "0.5.0"
default-features = false
features = ["json"]
